# Generated by Django 3.2.4 on 2021-06-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0002_remove_emp_emp_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emp',
        ),
        migrations.DeleteModel(
            name='Emp_Profile',
        ),
    ]
